language: bash

sudo: required

install:
    - PATH=$PWD/bin:$PATH
    - jujube -f echo 'Installing jujube'
    - sed -i -e "s/#Server/Server/" ~/.jujube/etc/pacman.d/mirrorlist
    - jujube -f pacman --noconfirm -Syy
    - jujube -f pacman --noconfirm -S base-devel

script:
    - ./tests/test_all.sh
# Test on installing package from AUR
    - jujube -f yaourt --noconfirm -S tcptraceroute
    - sudo $PWD/bin/jujube -r tcptraceroute localhost
# Test on installing package from official repo
    - jujube -f pacman --noconfirm -S tree
    - jujube -f tree
# Test on installing package from official repo with root access
    - jujube -f pacman --noconfirm -S iftop
    - sudo bin/jujube -r iftop -t -s 5
    - yes | jujube -d
