language: bash

install:
    - PATH=$PWD/bin:$PATH
    - juju -f echo 'Installing juju'

script:
    - sed -i -e "s/#Server/Server/" ~/.juju/etc/pacman.d/mirrorlist
    - juju -f pacman --noconfirm -Syy
    - juju -f pacman --noconfirm -S base-devel
# Test on installing package from AUR (issue #58)
    #- juju -f yaourt --noconfirm -S tcptraceroute
    #- juju -f tcptraceroute localhost
# Test on installing package from official repo
    - juju -f pacman --noconfirm -S sysstat
    - juju -f iostat
