language: bash

sudo: required

install:
    - PATH=$PWD/bin:$PATH
    - junest --fakeroot echo 'Installing junest'

script:
    - ./tests/test_all.sh
    - junest --check ./bin/junest
    - yes | junest --delete
